name: hello-world
on:
  push:
    tags:
      - 'Stg.V[0-9]+.[0-9]+'
      - 'Prd.v[0-9]+'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
